### ISSUE TITLE
Targeting and .saferc Format Overhaul

### ISSUE THREAD

**Issue by jhunt** [starkandwayne/safe#115]
It's time to overhaul how `~/.saferc` is formatted, and take care of a few other issues in the process (namely #114 and #100).

New format:

```
current: some-alias
targets:
  some-alias:
    url: https://vault:8200
    skip_verify: false
```

When we list these via `safe targets`, show any URLs not over HTTPS as insecure, as well as any HTTPS urls with a `skip_verify` of true.

Additionally, a new `-t` / `--target` flag should be introduced to allow any safe command to specify a target (by alias), but only for the duration of the command chain.  This would allow the following:

```
safe -t old-vault export | safe -t new-vault import
```

with no race condition.
