### ISSUE TITLE
safe silently fails when given a bad target

### ISSUE THREAD

**Issue by teancom** [starkandwayne/safe#153]
A user gave `safe target` the URL of the vault instance (`https://1.2.3.4:8200`), instead of the `name` of the vault as defined in their `~/.saferc`. That was accepted, and updated the `current:` line to be the URL. They were then able to successfully authenticate, but it did not add a token to the file. I verified that if they put in a bad password, they would get an error, so they were definitely hitting the vault server they had targeted. But trying to use safe didn't work, because of the lack of token.

Example `~/.saferc` after running the "bad" `safe target` and a "successful" `safe auth ldap`:

```
version: 1
current: https://1.2.3.4:8200
vaults:
  aws-vault-1:
    url: https://1.2.3.4:8200
    token: ""
    skip_verify: false
```

Expected behavior: `safe target` warns about targeting an undefined vault, and doesn't get into a weird halfway working state.
