### ISSUE TITLE
support bcrypt-ing passwords

### ISSUE THREAD

**Issue by thomasmmitchell** [starkandwayne/safe#158]
The concourse 4.0.0+ basic_auth users require that their passwords are provided in bcrypt.

```
 add_local_users:
    description: |
      List of local concourse users to add with their bcrypted passwords.
      bcrypted password must have a strength of 10 or higher or the user will not be able to login
    default: []
    example:
    - some-user:$2a$10$sKZelZprWWcBAWbp28rB1uFef0Ybxsiqh05uo.H8EIm0sWc6IZGJu
    - some-other-user:$2a$10$.YIYH.5EWQcCvfE49xH/.OhIhGFiNtn.tQq.4pznpcrqZvoLxuKeC
```

Adding this to safe would make adding this into the genesis kit a lot smoother.
